### ISSUE TITLE
Can this project work on browser?

### ISSUE THREAD

**Issue by axipo** [lillallol/outline-pdf#1]
Hello, this project is very helpful. It can work on node js runtime, I wonder can it support browser (pure frontend) ?

**Comment by lillallol** [comment]
@axipo I will try to make some minor changes so that it works also on the browser. I will respond back when I am done.

**Comment by lillallol** [comment]
@axipo Take a look [here](https://github.com/lillallol/outline-pdf#browser). Try it and then tell me if it is ok with your use case?

**Comment by axipo** [comment]
Yes, it works! Thanks for your help 👍
