### ISSUE TITLE
Does the library support Unicode?

### ISSUE THREAD

**Issue by axipo** [lillallol/outline-pdf#2]
It seems that it doesn't support Unicode characters. 
Since I'm not a pdf expert, I don't know whether it's hard to support this feature. I found [some info](https://github.com/Hopding/pdf-lib#fonts-and-unicode) from pdf-lib project, and it looks like that there are many details to consider.

**Comment by lillallol** [comment]
@axipo  Can you please provide me with a minimally reproducible example in which my module fails.

**Comment by axipo** [comment]
Sure, I replaced some demo code:
```
outlinePdf.outline = `
    1||Ω 1
    2|-|Some random title 2
    -3|--|Some random title 3
    4|---|Some random title 4
    5|---|Some random title 5
    6|-|Some random title 6
    7||Some random title 7
`;
```
And the output toc looks like:
![image](https://user-images.githubusercontent.com/57408162/102088469-ec263000-3e55-11eb-901b-e067808e3fe9.png)

**Comment by lillallol** [comment]
@axipo I will try to find a solution but I think it will take some time. I will inform you when I am finished.

**Comment by axipo** [comment]
@lillallol Thanks very much. This project is the only solution to add TOC for pdf file on browser I found. 👍

**Comment by lillallol** [comment]
@axipo So I looked at the link you gave me. It does not work for the outline case so [I opened an issue in pdf-lib](https://github.com/Hopding/pdf-lib/issues/711). I am not expecting to get an answer back soon.

**Comment by lillallol** [comment]
@axipo I published a new patch. Check if it fixes your issue.

**Comment by axipo** [comment]
Yes, it works, thank you so much. @lillallol
